config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about" => "pages#about"
  resources :signups
  get "/thanks" => "pages#thanks"

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def thanks
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @signup=Signup.new
  end
  
  def create
    @signup = Signup.new(signup_params)
    if @signup.save
      redirect_to '/thanks'
     else
      render 'new'
    end 
  end 
  
  private
    def signup_params
   params.require(:signup).permit(:firstname, :email)
    end 
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width,minimum-scale=1">
    <!-- Include a Sidr bundled CSS theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<a id="simple-menu" href="#sidr">Toggle menu</a>

<div id="sidr">
  <!-- Your content -->
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li class="active"> <%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", new_signup_path %></li>
  </ul>
</div>


<%= yield %>
  <div class="footer"> <div class="container"> <p>A Yumio Project</p> </div> </div>
  
  <script data-turbolinks-track="true" src="/assets/application-5ec8317a69c812470d7789bf2f91d0dd.js"></script>
  
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Include jQuery -->
    <script src="//cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
    <!-- Include the Sidr JS -->
    <script src="//cdn.jsdelivr.net/jquery.sidr/2.2.1/jquery.sidr.min.js"></script>

  <script>
$(document).ready(function() {
  $('#simple-menu').sidr();
});
</script>
  </body>
</html>

app/views/pages/about.html.erb
 <div class="about-main">
   <img alt="Open" class="icon-menu" src="/assets/open-9688b19dacd0cc7d027490776ace74ff.svg" width="24px" /> 
   <div class="content container"> 
     <h1>Relive your favorite memories</h1> 
   </div> 
</div>

<div class="about-supporting">
  <div class="container"> 
    <h2>No more sorting through photos</h2> 
    <p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p> 
    <a class="btn btn-primary" <%= link_to "Sign Up", new_signup_path %>  </a>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-main">
  <div class="row" >
    <div class="content col-md-6 col-md-offset-6"> 
      <h1>Travel Stories</h1>
      <p><a class="btn btn-primary" href="about">Learn more</a></p> 
      </div>
   </div>
</div> 
<div class="home-supporting">
  <div class="container"> 
    <h2>Relive and share your adventures</h2> 
    <p>Stories automatically creates a digital journal filled with only your best photos.</p> 
  </div>
</div>
<div class="home-secondary"> 
  <div class="container"> 
  </div> 
</div>
<div class="home-about"> 
  <div class="container">
    <h2>Discover Stories</h2> 
    <p class="btn btn-primary">
         <%= link_to "Learn more", about_path %> </p>
  </div>
</div> 

app/views/pages/thanks.html.erb
<h1>
  THANKS!
</h1>

app/views/signups/new.html.erb
<h1>
  Sign Ups
</h1>

<%= form_for(@signup) do |signup| %>
	<div class="field">
   First Name <%= signup.text_area :firstname  %> <br>email
    <%= signup.text_area :email %>
  </div>
  <div class="actions">
    <%= signup.submit "Signup" %>
</div>
  <% end %> 
  
</div>